name: Download CSV with Selenium

on:
  schedule:
    - cron: "30 9 * * 0-4"
  workflow_dispatch:

jobs:
  download_csv:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # - uses: browser-actions/setup-chrome@v1
      #   with:
      #     install-chromedriver: true

      - name: Install dependencies
        run: pip install -r requirements.txt selenium --upgrade

      - name: Run Selenium Script
        run: python main.py

      - name: Commit data
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git status
          git add -A
          git commit -m "Add NEPSE data for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
